# Generated by Django 5.1.1 on 2024-10-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displaydata',
            old_name='locationn',
            new_name='location',
        ),
    ]
